import Tree from './tree'; // Assumes your main class file is named tree.js

describe('Binary Search Tree - Core and Private Logic Verification', () => {
    let bst;
    // We use a clean, predictable array to map out the exact structural expectations
    const initialArray = [1, 2, 3, 4, 5, 6, 7]; 

    beforeEach(() => {
        bst = new Tree(initialArray);
    });

    // 1. Structural Verification of the private #buildTree method
    test('#buildTree structural integrity check via public root', () => {
        // Check the absolute top root level
        expect(bst.root).not.toBeNull();
        expect(bst.root.value).toBe(4);

        // Check the left subtree structure generated by the recursion
        const leftSubtree = bst.root.left;
        expect(leftSubtree.value).toBe(2);
        expect(leftSubtree.left.value).toBe(1);
        expect(leftSubtree.right.value).toBe(3);

        // Check the right subtree structure generated by the recursion
        const rightSubtree = bst.root.right;
        expect(rightSubtree.value).toBe(6);
        expect(rightSubtree.left.value).toBe(5);
        expect(rightSubtree.right.value).toBe(7);
    });

    test('#buildTree leaves terminal branches as null (base case check)', () => {
        const deepestLeaf = bst.root.left.left; // This is node with value 1
        expect(deepestLeaf.value).toBe(1);
        
        // Verifies your base case (start > end -> return null) worked perfectly
        expect(deepestLeaf.left).toBeNull();
        expect(deepestLeaf.right).toBeNull();
    });
});

describe('Binary Search Tree - Full Feature Operations', () => {
    let bst;
    const initialArray = [1, 7, 4, 23, 8, 9, 4, 3, 5, 7, 9, 67, 6345];
    // Expected sorted, unique array: [1, 3, 4, 5, 7, 8, 9, 23, 67, 6345]

    beforeEach(() => {
        bst = new Tree(initialArray);
    });

    // 2. Insert Method
    test('insert() should add a new leaf node at the correct location', () => {
        bst.insert(6);
        expect(bst.find(6)).not.toBeNull();
        expect(bst.find(6).value).toBe(6);
    });

    // 3. Delete Method
    test('deleteItem() should remove a node from the tree safely', () => {
        bst.insert(6);
        expect(bst.find(6)).not.toBeNull();
        
        bst.deleteItem(6);
        expect(bst.find(6)).toBeNull();
    });

    // 4. Find Method
    test('find() should return the node matching the given value, or null if missing', () => {
        const foundNode = bst.find(23);
        expect(foundNode).not.toBeNull();
        expect(foundNode.value).toBe(23);
        expect(bst.find(999)).toBeNull();
    });

    // 5. Breadth-First Level Order Traversal
    test('levelOrder() should traverse the tree in breadth-first order', () => {
        const result = [];
        bst.levelOrder((node) => result.push(node.value));
        
        // Root-first level tracking check (Assuming 7 or 8 as root depending on rounding)
        expect(result[0]).toBe(bst.root.value);
        expect(result.length).toBe(10); // 10 unique elements
    });

    // 6. Depth-First In-Order Traversal
    test('inOrder() should yield elements in strictly sorted order', () => {
        const result = [];
        bst.inOrder((node) => result.push(node.value));
        expect(result).toEqual([1, 3, 4, 5, 7, 8, 9, 23, 67, 6345]);
    });

    // 7. Depth-First Pre-Order Traversal
    test('preOrder() should traverse roots before their children', () => {
        const result = [];
        bst.preOrder((node) => result.push(node.value));
        expect(result[0]).toBe(bst.root.value);
    });

    // 8. Depth-First Post-Order Traversal
    test('postOrder() should traverse children before their roots', () => {
        const result = [];
        bst.postOrder((node) => result.push(node.value));
        expect(result[result.length - 1]).toBe(bst.root.value);
    });

    // 9. Height Method
    test('height() should return the distance from node to its lowest leaf', () => {
        // Height of a leaf node should be 0
        const leafNode = bst.find(6345);
        expect(bst.height(leafNode)).toBe(0);
    });

    // 10. Depth Method
    test('depth() should return distance from root to target node', () => {
        expect(bst.depth(bst.root)).toBe(0);
    });

    // 11. IsBalanced Check Method
    test('isBalanced() should confirm balanced state', () => {
        expect(bst.isBalanced()).toBe(true);
        
        // Unbalance it artificially by forcing a long line down one branch
        bst.insert(7000);
        bst.insert(8000);
        bst.insert(9000);
        expect(bst.isBalanced()).toBe(false);
    });

    // 12. Rebalance Method
    test('rebalance() should take an unbalanced tree and make it balanced again', () => {
        bst.insert(7000);
        bst.insert(8000);
        bst.insert(9000);
        expect(bst.isBalanced()).toBe(false);

        bst.rebalance();
        expect(bst.isBalanced()).toBe(true);
    });
});